project:
  type: book
  output-dir: docs

book:
  title: "TA Handbook"
  reader-mode: true

  author: "Department of Statistics and Applied Probability at UCSB"
  date: ""

  page-footer:
    left: |
      Â©2023
    right: |
      This book was built with
      <a href="https://quarto.org/" target="_blank">Quarto</a>.
  chapters:
    - index.qmd
    - part: "**Preliminaries**"
      chapters:
        - Part_0_Basics/mission.qmd
        - Part_0_Basics/contacts.qmd
    - part: "**Expectations for Teaching Assistants**"
      chapters:
        - Part_1_TA_Expectations/descrip_of_duties.qmd
        - Part_1_TA_Expectations/comm.qmd
        - Part_1_TA_Expectations/workload.qmd
        - Part_1_TA_Expectations/sections.qmd
        - Part_1_TA_Expectations/office_hours.qmd
        - Part_1_TA_Expectations/grading.qmd
        - Part_1_TA_Expectations/course_materials.qmd
    - part: "**Hiring Procedures**"
      chapters:
        - Part_2_Hiring_Procedures/TAApplication.qmd
        - Part_2_Hiring_Procedures/SectionAssign.qmd
    - part: "**FAQ (Frequently Asked Questions)**"
      chapters:
        - Part_7_FAQ/electronic_resources.qmd
        - Part_7_FAQ/office_supplies.qmd

  downloads: [pdf, epub]

  favicon: Images/Logos_Icons/book-solid.svg

  sidebar:
    search: true
    logo: "Images/Logos_Icons/pstat_logo.svg"
    title: "**TA Handbook**"

bibliography: references.bib

format:
  html:
    theme:
      light: [simplex, styles.scss]
      dark: darkly
    code-link: true

  pdf:
    documentclass: scrreprt
    linkcolor: purple
